num_features: 4
num_nodes: 16
hidden_dim: 64
hidden_channels: 64
batch_size: 1
train_test_split_ratio: 0.8
learning_rate: 0.001
weight_decay: 5e-4
epochs: 100
patience: 30
model_path: src/models/
bond_length: 175
beta: 0.007 
data_path: src/data/
molecule: BH
machine: Guadalupe

